let mongoose = require('mongoose')

let Display=mongoose.Schema({
    Home:[{
        name:{
            type:String,
            required:true
        },
        image:{
            type:String,
            required:true
        },
        detail:{
            type:String,
            required:true
        },
        social:[{
            icon:{
                type:String,
                required:true
            },
            link:{
                type:String,
                required:true
            } 
        }]
    }],
    About:[{
        name:{
            type:String,
            required:true
        },
        title:{
            type:String,
            required:true 
        },
        image:{
            type:String,
            required:true
        },
        desc:{
            type:String,
            required:true
        },
        info:[{
            firstname:{
                type:String,
                required:true
            },
            lastname:{
                type:String,
                required:true
            },
            Add:{
                type:String,
                required:true
            },
            Age:{
                type:String,
                required:true
            },
            Phone:{
                type:Number,
                required:true
            },
            Email:{
                type:String,
                required:true
            },
            Town:{
                type:String,
                required:true
            },
            Lang:{
                type:String,
                required:true
            },
            Nationality:{
                type:String,
                required:true
            },
            freelancer:{
                type:String,
                required:true
            }
        }],
        skills:[{
            name:{
                type:String,
                required:true
            },
            number:{
                type:Number,
                required:true
            }
        }],
        facts:[{
            title:{
                type:String,
                required:true
            },
            info:{
                type:String,
                required:true
            }
        }],
        interest:[{
            icon:{
                type:String,
                required:true
            },
            title:{
                type:String,
                required:true
            }
        }],
        education:[{
            title:{
                type:String,
                required:true
            },
            time$loc:{
                type:String,
                required:true
            },
            desc:{
                type:String,
            }
        }]
    }],
    Contact:[{
        add:{
            type:String,
            required:true
        },
        iframe:{
            type:String,
            required:true
        },
        quote_title:{
            type:String,
            required:true
        },
        quote:{
            type:String,
            required:true
        },
        social:[{
            icon:{
                type:String,
                required:true
            },
            link:{
                type:String,
                required:true
            } 
        }],
        info:[{
            mail:{
                type:String,
                required:true
            },
            number:{
                type:Number,
                required:true
            }
        }]
    }],
    Blog:[{
        image:{
            type:String,
            required:true
        },
        Date:{
            type:String
        },
        Owner:{
            type:String,
            required:true
        },
        Title:{
            type:String,
            required:true
        },
        Content:{
            type:String,
            required:true
        }
    }],
    Project:[{
        link:{
            type:String,
            required:true
        },
        image:{
            type:String,
            required:true
        }
    }]
})

let ContentInfo=mongoose.model("Content",Display)
module.exports=ContentInfo